# Nixpacks configuration for Remix + Vite + Shopify app
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm ci --omit=dev && npm cache clean --force && npm remove @shopify/cli"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run docker-start"
